FROM maven:3.5.4-jdk-8

RUN mkdir /nodejs
ADD ./nodejs/ /nodejs/

ENV NODE_VERSION 10.19.0
ENV YARN_VERSION 1.22.0

RUN cd /nodejs \
  && tar -xJf "node-v$NODE_VERSION-linux-x64.tar.xz" -C /usr/local/ --strip-components=1 --no-same-owner \
  && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
  \
  && mkdir -p /opt \
  && tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/ \
  && ln -s /opt/yarn-v$YARN_VERSION/bin/yarn /usr/local/bin/yarn \
  && ln -s /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg \
  \
  && cd \
  && rm -rf /nodejs
 

ENV DOCKER_CHANNEL stable
ENV DOCKER_VERSION 17.06.2-ce
ENV DOCKER_ARCH x86_64

RUN set -ex; \
	if ! curl -fL -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${DOCKER_ARCH}/docker-${DOCKER_VERSION}.tgz"; then \
		echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${DOCKER_ARCH}'"; \
		exit 1; \
	fi; \
	\
	tar --extract \
		--file docker.tgz \
		--strip-components 1 \
		--directory /usr/local/bin/ \
	; \
	rm docker.tgz; \
	\
	dockerd -v; \
	docker -v


COPY modprobe.sh /usr/local/bin/modprobe
COPY docker-entrypoint.sh /usr/local/bin/

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["sh"]
